version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    reviewers:
      - 'better-salmon'
    versioning-strategy: increase
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: 'eslint'
        versions: ['9.x.x']
      - dependency-name: '@types/eslint'
        versions: ['9.x.x']
      - dependency-name: '@typescript-eslint/eslint-plugin'
        versions: ['8.x.x']
      - dependency-name: '@typescript-eslint/parser'
        versions: ['8.x.x']
      - dependency-name: 'lru-cache'
        versions: ['11.x.x']
    groups:
      next-js:
        patterns:
          - 'next'
          - '@next/eslint-plugin-next'
      turbo:
        patterns:
          - 'turbo'
          - 'eslint-config-turbo'
      definitely-typed:
        patterns:
          - '@types/*'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      pino:
        patterns:
          - 'pino'
          - 'pino-pretty'
      nextra:
        patterns:
          - 'nextra'
          - 'nextra-theme-docs'
      eslint:
        patterns:
          - 'eslint'
          - '@types/eslint'
          - '@typescript-eslint/eslint-plugin'
          - '@typescript-eslint/parser'
