version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    reviewers:
      - 'better-salmon'
    versioning-strategy: increase
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: 'lru-cache'
        versions: ['>=11.0.0']
    groups:
      next-js:
        patterns:
          - 'next'
          - '@next/eslint-plugin-next'
      turbo:
        patterns:
          - 'turbo'
          - 'eslint-plugin-turbo'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      pino:
        patterns:
          - 'pino'
          - 'pino-pretty'
      nextra:
        patterns:
          - 'nextra'
          - 'nextra-theme-docs'
      eslint:
        patterns:
          - 'eslint'
          - '@eslint/js'
          - 'eslint-config-prettier'
          - 'eslint-plugin-react'
          - 'eslint-plugin-react-hooks'
          - 'eslint-plugin-turbo'
          - 'globals'
          - 'typescript-eslint'
