version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    reviewers:
      - 'better-salmon'
    versioning-strategy: increase
    open-pull-requests-limit: 20
    # ignore:
    #   - dependency-name: 'next'
    #     versions: ['14.x.x']
    #   - dependency-name: '@next/eslint-plugin-next'
    #     versions: ['14.x.x']
    groups:
      next-js:
        patterns:
          - 'next'
          - '@next/eslint-plugin-next'
      turbo:
        patterns:
          - 'turbo'
          - 'eslint-config-turbo'
      definitely-typed:
        patterns:
          - '@types/*'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      pino:
        patterns:
          - 'pino'
          - 'pino-pretty'
      nextra:
        patterns:
          - 'nextra'
          - 'nextra-theme-docs'
      eslint:
        patterns:
          - 'eslint'
          - '@types/eslint'
          - '@typescript-eslint/eslint-plugin'
          - '@typescript-eslint/parser'
