version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    reviewers:
      - 'better-salmon'
    versioning-strategy: increase
    open-pull-requests-limit: 20
    groups:
      next-js:
        patterns:
          - 'next'
          - '@next/eslint-plugin-next'
      turbo:
        patterns:
          - 'turbo'
          - 'eslint-config-turbo'
      definitely-typed:
        patterns:
          - '@types/*'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      pino:
        patterns:
          - 'pino'
          - 'pino-pretty'
