name: Deploy docs to Pages

on:
  push:
    branches: ['canary']
    paths:
      - 'docs/cache-handler-docs/**'
      - '.github/workflows/deploy-docs.yml'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          check-latest: true
          cache: 'npm'
      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next
          generator_config_file: ./docs/cache-handler-docs/next.config.js
      - name: Install dependencies
        run: npm ci
      - name: Build with Next.js
        run: npm run build:docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/cache-handler-docs/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
