name: Release

on:
  push:
    branches:
      - canary

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install Dependencies
        run: npm ci

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release
          version: npm run version-packages
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add dist-tags
        if: steps.changesets.outputs.published == 'true'
        id: dist-tags
        uses: ./.github/actions/add-dist-tags
        with:
          publishedPackages: ${{ steps.changesets.outputs.publishedPackages }}
          published: ${{ steps.changesets.outputs.published }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
