name: Release
env:
  CI: true
on:
  push:
    branches:
      - canary

permissions:
  contents: write
  pull-requests: write
  packages: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          check-latest: true
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Build packages
        run: npm run build:packages
      - name: Check code style
        run: npm run codestyle:check
      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run ci:publish
          version: npm run ci:version
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add dist-tags
        if: steps.changesets.outputs.published == 'true'
        id: dist-tags
        uses: ./.github/actions/add-dist-tags
        with:
          publishedPackages: ${{ steps.changesets.outputs.publishedPackages }}
          published: ${{ steps.changesets.outputs.published }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
