name: Tests
on:
  push:
    branches: [canary]
  pull_request:
    branches: [canary]
jobs:
  test:
    name: 'Test all'
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis/redis-stack-server:latest
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    container:
      image: mcr.microsoft.com/playwright:v1.40.1-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Run unit tests
        run: npm test
      - name: Build Next.js app and run tests
        run: |
          npm run start -w backend &
          npm run build:app
          npm run e2e
        env:
          REDIS_URL: redis://localhost:6379
