name: Check Docs Build
on:
  pull_request:
    branches: [canary]
    paths:
      - '.github/workflows/test-docs.yml'
      - 'docs/cache-handler-docs/**'
      - 'internal/eslint-config/**'
      - 'internal/prettier-config/**'
      - 'package.json'
      - 'biome.json'
      - '.prettierrc.json'
jobs:
  test:
    name: 'check-docs-build'
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          check-latest: true
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Check code style
        run: npm run codestyle:check
      - name: Build docs
        run: npm run build:docs
