name: Check Docs Build
env:
  CI: true
on:
  pull_request:
    types: [opened, synchronize]
    branches: [canary]
    paths:
      - '.github/workflows/test-docs.yml'
      - 'docs/cache-handler-docs/**'
      - 'internal/eslint-config/**'
      - 'package.json'
      - 'biome.json'
      - 'prettier.config.js'
jobs:
  test:
    name: 'check-docs-build'
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          check-latest: true
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build docs
        run: pnpm build:docs
