name: Tests
on:
  push:
    branches: [canary]
  pull_request:
    branches: [canary]
jobs:
  test:
    name: 'Test all'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.38.1-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Run Jest tests
        run: npm test
      - name: Build Next.js app and run tests
        run: |
          npm run start -w @neshca/backend &
          npm run start -w @neshca/server &
          npm run build:app
          npm run e2e
